name: Bump Version Tag

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        git config --global user.email "treeder+actions@gmail.com"
        git config --global user.name "Actions"
        wget -O - https://raw.githubusercontent.com/treeder/bump/master/gitbump.sh | bash
